image: Visual Studio 2017

environment:
  # Python version used
  MICROPY_CPYTHON3: c:/python34/python.exe

init:
  # Set build version number to commit to be travis-like
- ps: Update-AppveyorBuild -Version $env:appveyor_repo_commit.substring(0,8)

configuration:
- Debug
- Release

platform:
- x86
- x64

before_build:
  # Enable MICROPY_STACK_CHECK so the tests for recursivity pass
- ps: "@\"\n<?xml version=\"1.0\" encoding=\"utf-8\"?> \n<Project xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n  <ItemDefinitionGroup>\n    <ClCompile>\n      <PreprocessorDefinitions>%(PreprocessorDefinitions);MICROPY_STACK_CHECK=1</PreprocessorDefinitions>\n    </ClCompile>\n  </ItemDefinitionGroup>\n</Project>\n\"@ | Set-Content .\\windows\\msvc\\user.props"

build_script:
- cmd: >-
    msbuild windows/micropythoncore.vcxproj /p:platform=%platform%;configuration=%configuration%

    msbuild windows/micropython.vcxproj /p:platform=%platform%;configuration=%configuration%

test_script:
- cmd: >-
    cd tests

    %MICROPY_CPYTHON3% run-tests

skip_tags: true

deploy: off

nuget:
  disable_publish_on_pr: true
